<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMPaZsDu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMPaZsDu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMPaZsDu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMPaZsDu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMPaZsDu\App_KernelDevDebugContainer([
    'container.build_hash' => 'MPaZsDu',
    'container.build_id' => '4683c59d',
    'container.build_time' => 1690038047,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMPaZsDu');
