root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./app"
  cmd = "go build -o app main.go database.go cache.go accounts.go sessions.go api.go audit.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "testdata", ".vscode", ".idea"]
  exclude_file = ["Dockerfile", "Dockerfile.local", "docker-compose.yml"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
